<?php

return [
    'personnel' => [
        [
            'name' => 'Unang Mulkhan, Ph.D.',
            'role' => 'Research Director',
            'color' => 'primary',
            'icon' => 'flask-conical',
            'image' => 'images/team/002unang.webp',
            'summary' => 'Lead researcher dengan rekam jejak panjang dalam kajian dampak sosial-ekonomi, kebijakan ketenagakerjaan, serta monitoring dan evaluasi program pembangunan di kancah nasional maupun internasional.',
            'projects' => [
                ['title' => 'Impact assessment sosial-ekonomi kawasan industri perikanan, pekerja, dan serikat pekerja di Taiwan', 'client' => 'ISEAL', 'year' => '2025', 'role' => 'Lead Researcher'],
                ['title' => 'Impact assessment sosial-ekonomi kawasan industri seafood, pekerja, dan serikat pekerja di Indonesia', 'client' => 'OXFAM', 'year' => '2024', 'role' => 'Lead Researcher'],
                ['title' => 'Scoping rantai pasok industri elektronik pada kawasan industri, pekerja, dan serikat pekerja (SINERGI)', 'client' => 'ICF International', 'year' => '2023-2024', 'role' => 'Anggota Tim Riset'],
                ['title' => 'Scoping rantai pasok industri tembakau pada kawasan industri dan sosial-ekonomi komunitas lokal (SINERGI)', 'client' => 'ICF International', 'year' => '2023-2024', 'role' => 'Anggota Tim Riset'],
                ['title' => 'Program Aflateen+ di Indonesia, Nepal, dan Pakistan — evaluasi program sosial-ekonomi berbasis Randomised Control Trial (RCT)', 'client' => 'Aflatoun International, Amsterdam', 'year' => '2022-2024', 'role' => 'Lead Researcher'],
                ['title' => 'SDGs Diagnostic Acceleration — scoping, monitoring, evaluasi capaian SDGs, UNDP Diagnostic Simulator, dialog multi-pemangku kepentingan', 'client' => 'UNDP & Bappenas', 'year' => '2022', 'role' => 'National Policy Expert'],
                ['title' => 'Codesign — Sustainable, Resilient and Inclusive Public Spaces and Services (CIPSS)', 'client' => 'Swedish Institute / Lund University', 'year' => '2020-2024', 'role' => 'Lead Researcher'],
                ['title' => 'Handbook on the Context of SDGs in Asia Pacific — bagian monitoring & evaluasi', 'client' => 'Raoul Wallenberg Institute (RWI), Swedia', 'year' => '2019-2022', 'role' => 'Konsultan'],
                ['title' => 'Monitoring, evaluation, accountability, and learning (MEAL) untuk isu serikat pekerja dan petani di 5 provinsi Indonesia', 'client' => 'Mercy Corps Indonesia & UCLG ASPAC', 'year' => '2022', 'role' => 'MEAL Consultant'],
                ['title' => 'Kajian dampak sosial COVID-19 di 4 provinsi Indonesia', 'client' => 'Uni Eropa (EU)', 'year' => '2021', 'role' => 'Lead Consultant'],
                ['title' => 'Monitoring dan evaluasi capaian SDGs pemerintah daerah', 'client' => 'UCLG ASPAC', 'year' => '2021', 'role' => 'Lead Consultant'],
                ['title' => 'Integrasi SDGs dalam RTRW & RPJMD, analisis KLHS Provinsi Lampung, serta penyusunan regulasi pariwisata berkelanjutan dan isu perubahan iklim untuk DPRD & BAPPEDA Kota Bandar Lampung', 'client' => 'DPRD & BAPPEDA Kota Bandar Lampung / Pemprov Lampung', 'year' => '2021', 'role' => 'Expert / Resource Person'],
                ['title' => 'Urban Analysis Report Kota Pangkalpinang (Climate Resilient and Inclusive City/CRIC)', 'client' => 'ACR+ Belgia & Uni Eropa (EU)', 'year' => '2020', 'role' => 'Lead Consultant'],
                ['title' => 'Sustainable Local Economic Development di Vietnam', 'client' => 'CSEAS Kyoto University, Jepang', 'year' => '2019', 'role' => 'Peneliti'],
                ['title' => 'Kajian pembiayaan (financing study) mendukung rantai pasok dan komunitas berkelanjutan', 'client' => 'GIZ & SNV Netherlands Development Organisation', 'year' => '2025', 'role' => 'Lead Consultant'],
                ['title' => 'Survei organisasi bidang keberlanjutan di 5 negara ASEAN', 'client' => 'International Development Center of Japan (IDCJ)', 'year' => '2025', 'role' => 'Lead Consultant'],
                ['title' => 'Riset kebijakan bidang ketenagakerjaan serta keselamatan dan kesehatan kerja (OSH/HSE)', 'client' => 'Direktorat Pengawasan K3, Kementerian Ketenagakerjaan RI', 'year' => '2022-2025', 'role' => 'Konsultan Ahli'],
            ],
        ],
        [
            'name' => 'Dimas Bayu Arya Putra, M.B.A.',
            'role' => 'Research Manager',
            'color' => 'accent',
            'icon' => 'clipboard-check',
            'image' => 'images/team/004dimas.webp',
            'summary' => 'Research manager dengan fokus pada studi kelayakan pembangunan berkelanjutan, kebijakan keselamatan dan kesehatan kerja, serta kesetaraan gender di dunia kerja.',
            'projects' => [
                ['title' => 'Feasibility Study on Sustainable Economic Development in Bangka Belitung', 'client' => 'SNV Netherlands Development Organisation, ISCN & Bappenas', 'year' => '2025-2026', 'role' => 'Researcher'],
                ['title' => 'Occupational Health and Safety (OHS) Policy Review in Palm Oil Plantations', 'client' => 'Ministry of Manpower, Republic of Indonesia', 'year' => '2025', 'role' => 'Research Assistant'],
                ['title' => 'Workplace Gender Equality (WGE) Assessment of IDX-Listed Companies', 'client' => 'IBCWE & Katadata Collaboration', 'year' => '2025', 'role' => 'Research Analyst'],
            ],
        ],
        [
            'name' => 'Bayu Arie Fianto, Ph.D.',
            'role' => 'Senior Advisor, Housing Finance & Quantitative Research',
            'color' => 'primary',
            'icon' => 'bar-chart-3',
            'image' => 'images/team/003Bayu.webp',
            'summary' => 'Praktisi dan akademisi keuangan dengan keahlian pembiayaan inovatif, keuangan syariah, keuangan berkelanjutan, dan riset kuantitatif untuk pembangunan nasional maupun internasional.',
            'projects' => [
                ['title' => 'Preparation of Access to Sources of Additional and Innovative Finance for Commodity Supply Chain Actors to Support Public-Private and Community Partnership (PPCP) in the SOLUSI Project (Central Java, Central Sulawesi, Bangka Belitung)', 'client' => 'SNV Netherlands Development Organisation', 'year' => '2025', 'role' => 'Principal Investigator'],
                ['title' => 'UN Consultant for Islamic Finance in Indonesia', 'client' => 'United Nations (UN)', 'year' => '2025', 'role' => 'Principal Investigator'],
                ['title' => 'Improving EcoVadis Sustainability Assessment for Industrial Clients', 'client' => 'PT Arthawenasakti Gemilang', 'year' => '2025', 'role' => 'Principal Investigator'],
                ['title' => 'Training on Sustainable Finance Guideline for Bank Kalteng (USAID SEGAR)', 'client' => 'USAID', 'year' => '2025', 'role' => 'Principal Investigator'],
                ['title' => 'Integrated Sub-National Financing Framework (ISFF) Jawa Timur Advocacy and Communications Plan', 'client' => 'UNICEF Indonesia', 'year' => '2024', 'role' => 'Principal Investigator'],
                ['title' => 'Developing National Strategy on Innovative Finance for Climate Resilience and Biodiversity in Indonesian Land and Seascapes', 'client' => 'SNV Netherlands Development Organisation', 'year' => '2024', 'role' => 'Principal Investigator'],
                ['title' => 'Training KAG Path to Sustainability', 'client' => 'PT Kapal Api Global', 'year' => '2024', 'role' => 'Principal Investigator'],
                ['title' => 'Kajian Percepatan Pencapaian Pilar Sosial SDGs Indonesia', 'client' => 'Kemenko Bidang Pembangunan Manusia dan Kebudayaan (Kemenko PMK)', 'year' => '2023', 'role' => 'Principal Investigator'],
                ['title' => 'Kajian Sistem Penjaminan Simpanan (Deposit Insurance) bagi Lembaga Keuangan Mikro Syariah', 'client' => 'Komite Nasional Ekonomi dan Keuangan Syariah (KNEKS)', 'year' => '2021', 'role' => 'Principal Investigator'],
                ['title' => 'Peran Fintech Syariah dalam Mendukung Inklusi Keuangan Menurut Maqasid Al-Shariah', 'client' => 'Otoritas Jasa Keuangan (OJK)', 'year' => '2019', 'role' => 'Co-Investigator'],
                ['title' => 'Course Coordinator Research Method & Financial Management Research Methods (Metodologi Survei & Analisis Data)', 'client' => 'FEB Universitas Airlangga', 'year' => 'Berjalan', 'role' => 'Course Coordinator'],
            ],
        ],
    ],
];
