<?php

return [
    'articles' => [
        [
            'slug' => 'revisi-uu-keselamatan-kerja',
            'title' => 'Analisis Kebijakan Revisi UU No. 1 Tahun 1970 tentang Keselamatan Kerja',
            'category' => 'Kebijakan Publik',
            'date' => '2025',
            'reading_time' => '8 menit',
            'image' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            'excerpt' => 'Kajian komprehensif mengenai kebutuhan revisi undang-undang keselamatan kerja yang telah berlaku lebih dari lima dekade, serta rekomendasi pembaruan regulasi sesuai perkembangan industri modern.',
            'content' => '<p>Undang-Undang Nomor 1 Tahun 1970 tentang Keselamatan Kerja merupakan salah satu regulasi tertua di bidang K3 yang masih berlaku di Indonesia. Dalam lebih dari lima dekade berjalan, lanskap industri telah mengalami transformasi fundamental — dari industrialisasi massal menuju era industri 4.0 dengan otomatisasi, robotika, dan digitalisasi proses produksi.</p><p>PT Nusantara Techno Utama dipercaya oleh Pusat Pengembangan Kebijakan Ketenagakerjaan, Kementerian Ketenagakerjaan RI untuk melakukan analisis kebijakan revisi regulasi ini. Kajian ini mencakup pemetaan kesenjangan regulasi, benchmarking dengan standar ILO dan negara maju, serta formulasi rekomendasi kebijakan yang adaptif terhadap perkembangan teknologi dan jenis pekerjaan baru.</p><p>Temuan utama kajian ini menyoroti pentingnya pendekatan risiko-proaktif, integrasi aspek K3 digital, serta penguatan kapasitas pengawasan melalui transformasi digital. Rekomendasi yang dihasilkan diharapkan menjadi dasar penyusunan regulasi K3 yang lebih responsif dan berbasis bukti.</p>',
        ],
        [
            'slug' => 'dinamika-pengupahan-berkeadilan',
            'title' => 'Dinamika Pengupahan Berkeadilan dalam Harmonisasi Hubungan Industrial Berkelanjutan',
            'category' => 'Ketenagakerjaan',
            'date' => '2025',
            'reading_time' => '7 menit',
            'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            'excerpt' => 'Kajian mendalam tentang dinamika pengupahan berkeadilan di Indonesia, bagaimana upah minimum, struktur upah, dan produktivitas dapat diharmonisasikan untuk hubungan industrial yang berkelanjutan.',
            'content' => '<p>Pengupahan merupakan salah satu isu paling sensitif dalam hubungan industrial di Indonesia. Ketidakseimbangan antara upah, biaya hidup, dan produktivitas sering kali menjadi pemicu konflik antara pekerja dan pengusaha. Kajian ini dilakukan atas penugasan Direktorat Jenderal Pembinaan Hubungan Industrial dan Jaminan Sosial Tenaga Kerja, Kemnaker RI.</p><p>Analisis mencakup pemetaan dinamika pengupahan di berbagai sektor industri, studi komparatif mekanisme pengupahan di negara ASEAN, serta model simulasi dampak kebijakan pengupahan terhadap ketenagakerjaan dan investasi. Pendekatan kuantitatif dan kualitatif digunakan secara terintegrasi untuk menghasilkan rekomendasi kebijakan yang berimbang antara perlindungan pekerja dan daya saing industri.</p><p>Hasil kajian ini memberikan kerangka kerja (framework) bagi pemerintah dalam menyusun kebijakan pengupahan yang adil, transparan, dan berbasis data — mendukung harmonisasi hubungan industrial yang berkelanjutan di Indonesia.</p>',
        ],
        [
            'slug' => 'evaluasi-jaminan-pensiun',
            'title' => 'Evaluasi Penyelenggaraan Program Jaminan Pensiun',
            'category' => 'Jaminan Sosial',
            'date' => '2025',
            'reading_time' => '6 menit',
            'image' => 'https://images.unsplash.com/photo-1450101499163-c8848e968338?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            'excerpt' => 'Evaluasi menyeluruh terhadap penyelenggaraan program jaminan pensiun di Indonesia, mencakup efektivitas kepesertaan, kecukupan manfaat, dan keberlanjutan sistem.',
            'content' => '<p>Program Jaminan Pensiun merupakan pilar penting dalam sistem jaminan sosial ketenagakerjaan di Indonesia. Namun, cakupan kepesertaan masih relatif rendah, terutama di sektor pekerja tidak tetup dan pekerja informal. Kajian evaluasi ini ditugaskan oleh Ditjen PHIJSK, Kemnaker RI untuk mengidentifikasi tantangan dan peluang perbaikan sistem.</p><p>NTU melakukan evaluasi terhadap aspek kepesertaan, pengelolaan dana, kecukupan manfaat, dan keberlanjutan fiskal program. Studi ini mengintegrasikan data kuantitatif dari BPJS Ketenagakerjaan, wawancara mendalam dengan pemangku kepentingan, serta analisis komparatif dengan sistem jaminan pensiun di negara-negara ASEAN.</p><p>Rekomendasi yang dihasilkan mencakup perluasan cakupan kepesertaan, optimalisasi pengelolaan investasi dana pensiun, serta desain ulang mekanisme manfaat untuk meningkatkan kesejahteraan pekerja pascapensiun.</p>',
        ],
        [
            'slug' => 'sdgoals-diagnostic-acceleration',
            'title' => 'SDGs Diagnostic Acceleration: Monitoring & Evaluasi Capaian SDGs di Indonesia',
            'category' => 'Kebijakan Publik',
            'date' => '2022',
            'reading_time' => '5 menit',
            'image' => 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            'excerpt' => 'Peran NTU sebagai National Policy Expert dalam program UNDP-Bappenas untuk mempercepat pemantauan dan evaluasi capaian Tujuan Pembangunan Berkelanjutan (SDGs) di tingkat nasional.',
            'content' => '<p>Program SDGs Diagnostic Acceleration yang dilaksanakan oleh UNDP bekerja sama dengan Bappenas bertujuan mempercepat pemantauan dan evaluasi capaian Tujuan Pembangunan Berkelanjutan (SDGs) di Indonesia. Program ini menggunakan pendekatan inovatif termasuk UNDP Diagnostic Simulator untuk simulasi skenario pembangunan.</p><p>NTU melalui Research Director kami berperan sebagai National Policy Expert, memfasilitasi dialog multi-pemangku kepentingan dan mengkoordinasikan proses scoping serta monitoring capaian SDGs di berbagai sektor. Kerangka kerja yang dikembangkan mengintegrasikan data statistik nasional dengan indikator SDGs untuk menghasilkan pemetaan gap analysis yang komprehensif.</p><p>Kontribusi krusial dalam program ini memperkuat posisi NTU sebagai mitra tepercaya pemerintah dalam pengembangan kebijakan berbasis bukti untuk pembangunan berkelanjutan di Indonesia.</p>',
        ],
        [
            'slug' => 'pembiayaan-perumahan-pekerja',
            'title' => 'Pembiayaan Inovatif untuk Perumahan dan Kesejahteraan Pekerja',
            'category' => 'Riset',
            'date' => '2024',
            'reading_time' => '6 menit',
            'image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            'excerpt' => 'Kajian tentang mekanisme pembiayaan inovatif untuk akses perumahan pekerja, mencakup ability to pay, willingness to pay, dan skema pembiayaan berkelanjutan.',
            'content' => '<p>Akses perumahan yang layak merupakan salah satu tantangan terbesar bagi pekerja di Indonesia. Keterbatasan kemampuan membayar (ability to pay) dan berbagai hambatan struktural membuat program perumahan pekerja sulit terwujud tanpa pendekatan pembiayaan yang inovatif.</p><p>Tim riset NTU melakukan kajian mendalam tentang mekanisme pembiayaan perumahan pekerja, mengintegrasikan analisis kemampuan membayar (ATP), kemauan membayar (WTP), serta preferensi skema pembiayaan. Kajian ini menggunakan metode mixed-methods dengan survei kuantitatif skala besar dan wawancara mendalam.</p><p>Temuan utama mengidentifikasi skema pembiayaan berbasis tabungan, subsidi bertingkat, dan kemitraan public-private sebagai jalur paling prospektif untuk memperluas akses perumahan bagi kalangan pekerja berpenghasilan rendah hingga menengah.</p>',
        ],
        [
            'slug' => 'ekonomi-sirkular-pengelolaan-limbah',
            'title' => 'Ekonomi Sirkular dan Pengelolaan Limbah Industri: Pendekatan Berkelanjutan',
            'category' => 'Teknologi',
            'date' => '2024',
            'reading_time' => '5 menit',
            'image' => 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
            'excerpt' => 'Perspektif NTU tentang transformasi dari ekonomi linier ke sirkular, termasuk solusi pengelolaan limbah, waste-to-energy, dan pemulihan material untuk industri berkelanjutan.',
            'content' => '<p>Ekonomi sirkular menjadi paradigma baru dalam pengelolaan sumber daya dan limbah industri. Berbeda dengan model linier konvensional (ambil-buat-buang), ekonomi sirkular mengedepankan pengurangan limbah, penggunaan kembali material, dan daur ulang untuk menciptakan siklus produksi yang berkelanjutan.</p><p>Sebagai perusahaan yang bergerak di bidang teknologi lingkungan, NTU mengembangkan solusi terintegrasi yang mencakup pengolahan air limbah, pengumpulan dan pengolahan limbah B3, waste-to-energy, produksi kompos, serta pemulihan material logam dan non-logam. Pendekatan ini tidak hanya mengurangi dampak lingkungan tetapi juga menciptakan nilai ekonomi dari material yang sebelumnya dianggap limbah.</p><p>Kombinasi keahlian NTU dalam riset terapan dan teknologi lingkungan memungkinkan kami menawarkan solusi end-to-end — mulai dari kajian kelayakan, desain sistem pengelolaan, hingga implementasi yang sesuai dengan regulasi lingkungan nasional dan standar internasional.</p>',
        ],
    ],
];
